cabal.project
optics-sop/LICENSE
optics-sop/Setup.hs
optics-sop/optics-sop.cabal
optics-sop/src/Generics/SOP/Optics.hs
optics-sop/src/Optics/SOP.hs
optics-sop/src/Optics/SOP/ToTuple.hs

The library currently has two purposes:
- It defines optics that are useful for working with generics-sop.
- It provides generic functions that allow to derive lenses, prisms
and isomorphisms for suitable generic datatypes automatically.

Add optics-sop library.

---

optics-core/optics-core.cabal
optics-core/src/Data/Tuple/Optics.hs
optics-core/src/Optics/Equality.hs
optics-core/src/Optics/Fold.hs
optics-core/src/Optics/Getter.hs
optics-core/src/Optics/Internal.hs
optics-core/src/Optics/Internal/Equality.hs
optics-core/src/Optics/Internal/Fold.hs
optics-core/src/Optics/Internal/Getter.hs
optics-core/src/Optics/Internal/Iso.hs
optics-core/src/Optics/Internal/Lens.hs
optics-core/src/Optics/Internal/Prism.hs
optics-core/src/Optics/Internal/Review.hs
optics-core/src/Optics/Internal/Setter.hs
optics-core/src/Optics/Internal/Subtyping.hs
optics-core/src/Optics/Internal/Traversal.hs
optics-core/src/Optics/Iso.hs
optics-core/src/Optics/Lens.hs
optics-core/src/Optics/Optic.hs
optics-core/src/Optics/Prism.hs
optics-core/src/Optics/Review.hs
optics-core/src/Optics/Setter.hs
optics-core/src/Optics/Traversal.hs
optics-core/tests/Optics/Tests.hs
optics-sop/src/Generics/SOP/Optics.hs

This removes all mention of the `Constraints` type family from the public interface.
Should we also rename the `mk...` functions?

Hide Constraints type family

---

optics-core/optics-core.cabal
optics-core/src/Optics/Internal/Fold.hs
optics-core/src/Optics/Internal/Indexed.hs
optics-core/src/Optics/Internal/IxSetter.hs
optics-core/src/Optics/Internal/Optic/Types.hs
optics-core/src/Optics/Internal/Profunctor.hs
optics-core/src/Optics/Internal/Setter.hs
optics-core/src/Optics/Internal/Traversal.hs
optics-core/src/Optics/Internal/Utils.hs
optics-core/src/Optics/Unindexed.hs

Proof of concept for #25 for now (in particular I think we should have a class with associated function `unIx` instead of `unIxTraversal` etc.
I think it can look better when representing indices as in #41, then regular versions have to accept optics with any list of indices instead of two free type parameters.
@phadej thoughts?

Support for explicit downcasting indexed optics to regular ones

---

optics-sop/optics-sop.cabal
optics-sop/src/Generics/SOP/Optics.hs
optics-sop/src/Optics/SOP.hs
optics-sop/src/Optics/SOP/ToTuple.hs

`product` is a name from Prelude, so we use `productRep`, as it's
like `rep` but for products.

Resolve #42: rename record to productRep

---

optics-core/optics-core.cabal
optics-core/src/Optics/Internal/Indexed.hs
optics-core/src/Optics/Internal/Optic/Subtyping.hs
optics-core/src/Optics/Optic.hs

Solves #78.
I skipped the internal superclass because it actually makes things worse.
```haskell
λ> :t itraverseOf
itraverseOf
:: (Optics.Internal.Indexed.CheckIndicesInternal i,
Is k A_Traversal, Applicative f) =>
Optic k '[i] s t a b -> (i -> a -> f b) -> s -> f t
```
I don't think it's a big deal though as this class is only for helpful error messages.

Expose CheckIndices for haddock and cleaner signatures

---

optics-core/optics-core.cabal
optics-core/src/Optics/Arrow.hs
optics-core/src/Optics/Indexed.hs
optics-core/src/Optics/Internal/Indexed.hs
optics-core/src/Optics/Internal/Optic.hs
optics-core/src/Optics/Internal/Optic/Subtyping.hs
optics-core/src/Optics/Internal/Optic/TypeLevel.hs
optics-core/src/Optics/LensyReview.hs
optics-core/src/Optics/Prism.hs
optics-core/src/Optics/PrismaticGetter.hs
optics-core/src/Optics/Unindexed.hs

Helps to catch unneeded restriction of indices and we get to see how easy it's to avoid introducing it.

Use DataKinds only where it's needed

---

optics-core/src/Optics/Internal/Fold.hs
optics-core/src/Optics/Internal/IxFold.hs
optics-core/src/Optics/Internal/IxSetter.hs
optics-core/src/Optics/Internal/IxTraversal.hs
optics-core/src/Optics/Internal/Profunctor.hs
optics-core/src/Optics/IxFold.hs
optics-core/src/Optics/IxSetter.hs
optics-core/src/Optics/IxTraversal.hs
optics/tests/Optics/Tests.hs

Woohoo!
Now we get degradation of indexed optics without loss of efficiency in comparison to regular versions. And the implementation is surprisingly simple.

Implement equivalent of Conjoined from lens for efficient optics degradation

---

optics-core/src/Optics/AffineTraversal.hs
optics-core/src/Optics/Arrow.hs
optics-core/src/Optics/Internal/Concrete.hs
optics-core/src/Optics/Internal/Optic/Types.hs
optics-core/src/Optics/Internal/Profunctor.hs
optics-core/src/Optics/Prism.hs
optics-extra/optics-extra.cabal
optics-extra/src/Optics/At.hs
optics-extra/src/Optics/Cons.hs
optics-extra/src/Optics/Empty.hs
optics-extra/src/Optics/Extra.hs
optics/tests/Optics/Tests.hs

Fixes #30.
The first commit borrows some ideas from #98 to get affine traversals in VL form which are usually easier to define than using `atraversal` and can be more efficient.

Add VL affine traversal and Port Optics.At from lens

---

optics-core/src/Optics/Internal/Profunctor.hs
optics-core/src/Optics/IxSetter.hs
optics-core/src/Optics/Setter.hs
optics/src/Optics.hs

Addresses (1) and (2) of #115.
Should we have infix versions of `over'` and `set'` (`%!~` and `!~`)?

Add strict versions of (i)over and (i)set

---

optics-core/src/Optics/AffineFold.hs
optics-core/src/Optics/Getter.hs
optics-extra/optics-extra.cabal
optics-extra/src/Optics/Extra.hs
optics-extra/src/Optics/Extra/Internal/Zoom.hs
optics-extra/src/Optics/View.hs
optics-extra/src/Optics/Zoom.hs
optics/src/Optics.hs

Fixes #103.
There are three variations of both functions:
- `zoom`/`magnify` for `Lens`/`Getter`
- `zoomMaybe`/`magnifyMaybe` for `AffineTraversal`/`AffineFold`
- `zoomMany`/`magnifyMany` for `Traversal`/`Fold`

Port Zoom and Magnify from lens

---

optics-sop/src/Generics/SOP/Optics.hs
optics-sop/src/Optics/SOP.hs
optics-sop/src/Optics/SOP/ToTuple.hs

See #22.
Should the main `Optics` module re-export `Optics.SOP`?

Finish off haddocks for optics-sop

---

optics-core/src/Optics/AffineFold.hs
optics-core/src/Optics/AffineTraversal.hs
optics-core/src/Optics/Empty/Core.hs
optics-core/src/Optics/Prism.hs

Fixes #148. This makes the elimination/computation rules for `AffineTraversal` cleaner.

Move matching and isn't to AffineTraversal

---

optics-th/optics-th.cabal

The [breaking change in `0.3`](https://github.com/glguy/th-abstraction/blob/master/ChangeLog.md) appears to be irrelevant as `datatypeVars` is not used.
> Breaking change: the datatypeVars field of DatatypeInfo is now of type [TyVarBndr] instead of [Type], as it now refers to all of the bound type variables in the data type. The old datatypeVars field has been renamed to datatypeInstTypes to better reflect its purpose.

Increase bounds on th-abstraction

---

optics-core/src/Optics/Fold.hs
optics-core/src/Optics/IxTraversal.hs
optics-core/src/Optics/Traversal.hs
optics/src/Optics.hs

I added `unsafeFIltered` and `indices`. I also made `filtered` inline so that it's compatible with `lens`.
`unsafeFiltered` and `filtered` can be defined as affine traversal and fold, but I didn't do that because they have at most one target, so it doesn't make much sense to me

Make filtered inline, add unsafeFiltered and indices

---

optics-core/src/Optics/Re.hs

Without this we have
```hs
set @A_Lens . re
:: (ReversibleOptic k, ReversedOptic k ~ A_Lens) =>
Optic k NoIx b a t s -> b -> s -> t
```
but adding it gives
```hs
set @A_Lens . re :: Optic A_LensyReview NoIx b a t s -> b -> s -> t
```

ReversedOptic is an injective type family

---

optics-core/src/Optics/Indexed/Core.hs
optics-core/src/Optics/Internal/Optic.hs
optics-core/src/Optics/IxFold.hs
optics-core/src/Optics/IxTraversal.hs
optics-core/src/Optics/Optic.hs

Allows to put filtered, ifiltered and other such not-quite-optics
into the optic composition chain.
left-associativity is essential for this to work,
but it works nicely!

Add %& post-composition operator.

---

optics-th/src/Optics/TH.hs

Is it mentioned anywhere that `FlexibleInstances`, `MultiParamTypeClasses`, `UndecidableInstances` are needed? Should I enable them by default, when making `optics`?

Fix spelling in example

---

optics-core/optics-core.cabal
optics-core/src/Optics/Core.hs
optics-core/src/Optics/IxTraversal.hs
optics-core/src/Optics/ReadOnly.hs
optics-core/src/Optics/Traversal.hs
optics/optics.cabal
optics/src/Optics.hs

It's the equivalent of `getting` function from lens.
I didn't find `getting` to be a good name, but I'm not sure if `readOnly` is good either - suggestions welcome.

Support for turning read-write optics into their read-only counterparts

---

optics-core/src/Optics/Review.hs

This somehow snuck past when the other to... functions were culled.

Remove toReview

---

optics-core/src/Optics/AffineTraversal.hs
optics-core/src/Optics/IxAffineTraversal.hs
optics-core/src/Optics/IxLens.hs
optics-core/src/Optics/IxTraversal.hs
optics-core/src/Optics/Lens.hs

If `*VL` functions are not in the `Introduction` section, but at the end in the `van Laarhoven` section, people will have hard time discovering them, so I moved them up.

Make construction from VL optics more visible

---

optics-core/src/Optics/Indexed/Core.hs
optics-core/src/Optics/Internal/Optic.hs

Thanks to @kosmikus for the feedback.
This introduces some duplicate export warnings, but they should be fixed by #225.

Better documentation for composition of indexed optics

---

optics-th/optics-th.cabal

I spotted after releasing 0.1 (thanks to the matrix builder) that `optics-th` has an unnecessarily tight bound on `template-haskell`, which rules out GHC 8.8. This wasn't spotted before because our CI for 8.8 is still using `allow-newer`. I've made a Hackage revision of `optics-th` to relax this bound.

Relax optics-th bound on template-haskell

---

optics/optics.cabal

CI takes forever to build the dependencies.
https://travis-ci.org/well-typed/optics/builds/582262790?utm_source=github_status&utm_medium=notification

Disable building benchmarks for GHCJS CI as they're not run anyway

---

optics-core/src/Optics/Internal/Indexed.hs
optics-core/src/Optics/Internal/Optic.hs
optics-core/src/Optics/Internal/Optic/Subtyping.hs
optics-core/src/Optics/Internal/Optic/TypeLevel.hs
optics-core/src/Optics/Internal/Optic/Types.hs
optics-core/src/Optics/Optic.hs
optics/src/Optics.hs

Fixes #71. This improves the haddocks and repl use: 
```hs
*Optics.Core> :kind Optic
Optic :: OpticKind -> Indices -> * -> * -> * -> * -> *
```
We need to enable `TypeInType` for older GHCs. This has an effect on the parsing of `*`, so I've switched to `Type` in a few places.
Opinions on `Indices` vs `IxList`?

Introduce type synonyms for optic kind and indices

---

generic-optics/generic-optics.cabal
indexed-profunctors/CHANGELOG.md
indexed-profunctors/indexed-profunctors.cabal
optics-core/CHANGELOG.md
optics-core/optics-core.cabal
optics-core/src/Optics/Internal/Optic/TypeLevel.hs
optics-core/src/Optics/Internal/Optic/Types.hs
optics-core/src/Optics/Iso.hs
optics-extra/CHANGELOG.md
optics-extra/optics-extra.cabal
optics-extra/src/Optics/State.hs
optics-extra/src/Optics/View.hs
optics-sop/optics-sop.cabal
optics-th/CHANGELOG.md
optics-th/optics-th.cabal
optics-th/src/Optics/TH.hs
optics-vl/CHANGELOG.md
optics-vl/optics-vl.cabal
optics/CHANGELOG.md
optics/optics.cabal
template-haskell-optics/template-haskell-optics.cabal

Fixes #257. I've added changelogs, `@since` annotations, bumped the versions of published packages to 0.2, uploaded candidates:
* https://hackage.haskell.org/package/optics-core-0.2/candidate
* https://hackage.haskell.org/package/optics-extra-0.2/candidate
* https://hackage.haskell.org/package/optics-th-0.2/candidate
* https://hackage.haskell.org/package/optics-0.2/candidate
* https://hackage.haskell.org/package/optics-vl-0.2/candidate
This needs a release date, and I'd like to add more cross-package hyperlinks to the package descriptions, as I've done for `optics`. Anything else needed for the release?

Release 0.2

---

optics-core/src/Optics/Arrow.hs
optics-core/src/Optics/Cons/Core.hs
optics-core/src/Optics/Internal/Indexed.hs
optics-core/src/Optics/Internal/Utils.hs
optics-core/src/Optics/IxAffineFold.hs
optics-core/src/Optics/IxAffineTraversal.hs
optics-core/src/Optics/IxGetter.hs
optics-core/src/Optics/IxLens.hs
optics-core/src/Optics/IxTraversal.hs
optics-extra/src/Optics/Cons.hs

I noticed when comparing `isingular` to `ipre` that the latter was 15% slower, tracked it down to the fact that `iafolding` that `ipre` uses was using `uncurry` whereas `isingular` has regular pattern matching on a pair.

Use stricter uncurry for better performance

---

optics/optics.cabal
optics/tests/Optics/Tests.hs
optics/tests/Optics/Tests/Properties.hs

We do have inspection tests for these,
yet QuickCheck finds counter-examples.

Add computation QuickCheck properties

---

codegen/Subtypes.hs
optics-core/src/Optics/Internal/Optic.hs
optics-core/src/Optics/Internal/Optic/Subtyping.hs

Patch mostly by Ryan Scott, see
https://gitlab.haskell.org/RyanGlScott/head.hackage/blob/9fadfda472c80007e7a52471cf891587aa6b7465/patches/optics-core-0.2.patch
I rewrote `%%` def to make type-checker guess less

Make optics break less with simplified subsumption

---

optics-core/src/Optics/AffineFold.hs
optics-core/src/Optics/AffineTraversal.hs
optics-core/src/Optics/Indexed/Core.hs
optics-core/src/Optics/IxAffineFold.hs
optics-core/src/Optics/IxAffineTraversal.hs
optics/tests/Optics/Tests/Misc.hs

Fixes #293.
Note that the first commit breaks API as it renames two existing functions, but they're obscure enough that I'm pretty sure (almost) no one has used them.
Their new names correspond nicely with appropriate Fold/Traversal functions, so IMO it's worth it.

Add filteredBy/unsafeFilteredBy

---

optics-core/src/Optics/Internal/Optic.hs

Cherry-picked from #290, useful on its own.

Add hidden LabelOptic instance to postpone instance resolution

---

optics-core/src/Optics/IxAffineTraversal.hs
optics-core/src/Optics/IxTraversal.hs

Optics.IxTraversal still exports ignored, for backwards compatibility.

Generalise ignored to be an IxAffineTraversal instead of an IxTraversal

---

optics-core/src/Optics/AffineFold.hs
optics-core/src/Optics/Fold.hs
optics-core/src/Optics/IxAffineFold.hs
optics-core/src/Optics/IxAffineTraversal.hs
optics-core/src/Optics/IxFold.hs
optics-core/src/Optics/Optic.hs
optics/src/Optics.hs

Fixes #244. I came across some `lens` code using `<>` and wondered what the equivalent in `optics` would look like...

Document monoidal structures of Folds

---

metametapost/src/MetaMetaPost.hs
optics-core/src/Optics/Label.hs
optics-th/src/Optics/TH.hs
optics-th/src/Optics/TH/Internal/Product.hs
optics-th/src/Optics/TH/Internal/Sum.hs
optics/tests/Optics/Tests/Labels.hs

```haskell
data Test = Test { testX :: Int }
makeFieldLabels ''Test
x :: Lens' Test Int
x = #x
```
Before:
```
• No instance for LabelOptic "x" ‘A_Lens’ ‘Test’ ‘Test’ ‘Int’ ‘Int’
(maybe you forgot to define it or misspelled a name?)
• In the expression: #x
In an equation for ‘x’: x = #x
```
After:
```
• Couldn't match type ‘A_Lens’ with ‘An_Iso’
arising from the overloaded label ‘#x’
• In the expression: #x
In an equation for ‘x’: x = #x
```

Make optic kind a type equality for better type inference / errors

---

optics-th/optics-th.cabal
optics-th/src/Language/Haskell/TH/Optics/Internal.hs
optics-th/src/Optics/TH/Internal/Product.hs
optics-th/src/Optics/TH/Internal/Sum.hs
optics-th/src/Optics/TH/Internal/Utils.hs
optics-th/tests/Optics/TH/Tests.hs
template-haskell-optics/src/Language/Haskell/TH/Optics.hs

Existing check wasn't taking injective type families into account (and wasn't working properly really).

Make generation of LabelOptic instances aware of injective type families  and polymorphic kinds

---

optics-core/CHANGELOG.md
optics-core/src/Optics/IxAffineFold.hs
optics-extra/CHANGELOG.md
optics-th/CHANGELOG.md
optics-vl/CHANGELOG.md
optics/CHANGELOG.md

I propose ~~Monday~~Wednesday as the release date and have updated things appropriately and uploaded tentative package candidates. ~~The only significant change is that I propose to release `optics-vl` as `0.3` instead of `0.2.1`. While in theory the latter is permissible, it doesn't seem worth deviating from the version numbering of the other packages at this point. Please shout if you disagree.~~
* https://hackage.haskell.org/package/optics-core-0.3/candidate
* https://hackage.haskell.org/package/optics-extra-0.3/candidate
* https://hackage.haskell.org/package/optics-th-0.3/candidate
* https://hackage.haskell.org/package/optics-0.3/candidate
* https://hackage.haskell.org/package/optics-vl-0.2.1/candidate

Release 0.3

---

optics-core/src/Optics/Internal/Optic.hs

`Perhaps` is used by GHC and error message in `.Subtyping` module.

Improve error message in catch-all GeneralLabelOptic instance

---

optics-core/src/Optics/Internal/Optic.hs

Optimize away profunctor classes when profiling (#324)

---

optics-th/optics-th.cabal
optics-th/src/Optics/TH/Internal/Product.hs
optics-th/tests/Optics/TH/Tests/DuplicateRecordFields.hs

Fix declareFieldLabels or declareLenses with DuplicateRecordFields

---

optics-core/src/Optics/Fold.hs
optics-core/src/Optics/IxAffineTraversal.hs
optics-core/src/Optics/IxFold.hs
optics-core/src/Optics/IxTraversal.hs
optics-core/src/Optics/Traversal.hs
optics/benchmarks/traversals.hs
optics/src/Optics.hs
optics/tests/Optics/Tests/Misc.hs
optics/tests/Optics/Tests/Utils.hs

Fixes #331.
It's reasonably fast when compared to a hand-written version (and obliterates `lens`):
```
benchmarking misc/adjoin/hand-written
time                 30.16 ns   (29.32 ns .. 31.73 ns)
0.991 R²   (0.978 R² .. 1.000 R²)
mean                 30.34 ns   (29.49 ns .. 32.66 ns)
std dev              2.938 ns   (876.6 ps .. 5.151 ns)
variance introduced by outliers: 90% (severely inflated)
benchmarking misc/adjoin/adjoin
time                 65.72 ns   (65.14 ns .. 66.25 ns)
0.999 R²   (0.999 R² .. 1.000 R²)
mean                 65.72 ns   (65.10 ns .. 66.22 ns)
std dev              1.131 ns   (853.5 ps .. 1.562 ns)
variance introduced by outliers: 21% (moderately inflated)
benchmarking misc/adjoin/adjoin/lens
time                 3.952 μs   (3.911 μs .. 4.019 μs)
0.997 R²   (0.991 R² …
```

Add (i)adjoin

---

template-haskell-optics/src/Language/Haskell/TH/Optics.hs

This is largely a port of https://github.com/ekmett/lens/pull/912, as part of #337.
As regards the `case` statements associated with the body of the `HasTypeVars` and `SubstType` implementations: `lens` does not have a catchall `t -> pure t` case, instead electing to write out all the boring cases separately; this is indeed noisy and boring, but would have indicated the missing branch for the `ForallVisT` case, whereas the catchall case in this code hid it. I’m happy to write out the cases in toto should that be preferable.
Fixes #345.

Extend GHC 8.10 Template Haskell interface (#345)

---

template-haskell-optics/src/Language/Haskell/TH/Optics.hs

This is a port of the documentation changes in https://github.com/ekmett/lens/pull/856: the signatures of optics that differ between `template-haskell` versions are documented in Haddock.
Something that this refactor raised is whether `DataPrism’`’s definition should be exported, since it differs meaningfully between `template-haskell` versions, and indeed its accompanying comment to that effect is elided in the Haddock output. I’d be in favor of it, since it’s version-relevant, and there haven’t been any releases yet. I’ve chosen to do so here.
Fixes #252.

Describe versioning differences in template-haskell-optics API.

---

template-haskell-optics/template-haskell-optics.cabal

Currently `cabal check` objects due to the presence of `extra-doc-files`.

Fix cabal-version for template-haskell-optics

---

optics-th/src/Optics/TH/Internal/Product.hs
optics-th/src/Optics/TH/Internal/Sum.hs
optics-th/src/Optics/TH/Internal/Utils.hs

Fixes #342.
```haskell
unknown@electronics optics $ cabal repl optics-th
Build profile: -w ghc-8.10.2 -O1
In order, the following will be built (use -v for more details):
- optics-th-0.3.0.2 (lib) (file src/Optics/TH/Internal/Product.hs changed)
Preprocessing library for optics-th-0.3.0.2..
GHCi, version 8.10.2: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/unknown/.ghci
[1 of 5] Compiling Language.Haskell.TH.Optics.Internal ( src/Language/Haskell/TH/Optics/Internal.hs, interpreted )
[2 of 5] Compiling Optics.TH.Internal.Utils ( src/Optics/TH/Internal/Utils.hs, interpreted )
[3 of 5] Compiling Optics.TH.Internal.Sum ( src/Optics/TH/Internal/Sum.hs, interpreted )
[4 of 5] Compiling Optics.TH.Internal.Product ( src/Optics/TH/Internal/Product.hs, interpreted …
```

Print missing language extensions on TH generation of labels

---

optics-core/src/Optics/Internal/Optic/TypeLevel.hs
optics-core/src/Optics/Traversal.hs
optics/tests/Optics/Tests/Misc.hs
optics/tests/Optics/Tests/Utils.hs

It's a modified `gplate` from lens that behaves like `template` from `Data.Data.Lens`, but without the weirdness observed in https://github.com/ekmett/lens/issues/907.
We can port `Control.Lens.Plated` with that.

Port generalized gplate from lens

---

optics-core/src/Optics/Internal/Optic.hs
optics-core/src/Optics/Internal/Optic/TypeLevel.hs
optics-core/src/Optics/Optic.hs
optics/tests/Optics/Tests/Core.hs
optics/tests/Optics/Tests/Eta.hs
optics/tests/Optics/Tests/Misc.hs
optics/tests/Optics/Tests/Utils.hs

Fixes #396.
This doesn't slow compilation, I tested with a big project.

Remove unsafeCoerce from appendIndices and fix tests with GHC 9.0.1

---

codegen/Subtypes.hs
optics-core/src/Optics/Indexed/Core.hs
optics-core/src/Optics/Internal/Optic.hs
optics-core/src/Optics/Internal/Optic/Subtyping.hs
optics-core/src/Optics/Optic.hs
optics-core/src/Optics/ReadOnly.hs
optics/src/Optics.hs
optics/tests/Optics/Tests/Labels/Generic.hs

Somewhat related to https://gitlab.haskell.org/ghc/ghc/-/issues/19336 (it's a GHC bug, but it pushed me to find a solution for using a class for `Join` that works).
I wanted to do that for some time now, considering that the type signature of `%` was a bit messy, not to mention type signatures of generic optic functions (see e.g. #368). Now looks like a good time to do that since `Append` was also changed.
Now the signature of `%` is quite neat:
```haskell
>>> :t (%)
(%)
:: (JoinKinds k l m, AppendIndices is js ks) =>
Optic k is s t u v -> Optic l js u v a b -> Optic m ks s t a b
```
Also, now label compositions are somewhat readable:
```haskell
>>> :t #pets % traversed % #_GoldFish % #name
#pets % traversed % #_GoldFish % #name
:: (Traversable t1, JoinKinds k1 l1 m, JoinKinds k2 l2 k1, …
```

Turn Join into a class for neater type signatures

---

.github/workflows/haskell-ci.yml
cabal.haskell-ci
indexed-profunctors/indexed-profunctors.cabal
metametapost/metametapost.cabal
optics-core/optics-core.cabal
optics-extra/optics-extra.cabal
optics-sop/optics-sop.cabal
optics-sop/src/Optics/SOP.hs
optics-th/optics-th.cabal
optics-vl/optics-vl.cabal
optics/optics.cabal
template-haskell-optics/template-haskell-optics.cabal

Resolves #405 
- doctests for GHC-9.0 disabled (no release yet)
- `template-haskell-optics` isn't built with GHC-9.0 (also no support, #404)
- disable benchmarks too for GHC-9.0 (these could work with `allow-newer:` though).

Add GHC-9.0 CI job

---

optics-core/src/Optics/Prism.hs

and reformat surrounding examples to match
I was really surprised not to find `matching` called out more prominently in the `Prism` Haddock. Could we please add it? Now looks like:

Add 'matching' example

---

optics-core/src/Optics/Optic.hs
optics/src/Optics.hs

Tiny doc improvements that remove references to `Join` in favor of `JoinKinds`.
@adamgundry do these look good to you?

Remove references to Join from the documentation

---

.github/workflows/haskell-ci.yml
indexed-profunctors/indexed-profunctors.cabal
metametapost/metametapost.cabal
optics-core/optics-core.cabal
optics-extra/optics-extra.cabal
optics-sop/optics-sop.cabal
optics-th/optics-th.cabal
optics-vl/optics-vl.cabal
optics/optics.cabal
optics/tests/Optics/Tests/Core.hs
optics/tests/Optics/Tests/Eta.hs
optics/tests/Optics/Tests/Utils.hs
template-haskell-optics/template-haskell-optics.cabal

Add GHC-9.2 job too, except for optics-sop, metametapost (blocked on `generics-sop`) and `template-haskell-optics`
Resolves #436

Allow tamplate-haskell-2.18 in optics-th

---

codegen/Subtypes.hs
optics-core/src/Optics/Internal/Optic/Subtyping.hs
optics/src/Optics.hs
optics/tests/Optics/Tests/Core.hs
optics/tests/Optics/Tests/Utils.hs

Fixes #423 (to an extent).
Simpler than #424, but should make the situation strictly better.

Stop picking the catch-all JoinKinds instance if arguments match

---

optics-extra/optics-extra.cabal

The GHC-8.2 didn't ship `text`, so CI picks up `text-2.0` there.

Allow text-2.0

---

optics-core/src/Data/Maybe/Optics.hs

```haskell
o1 %? o2 = o1 % _Just % o2
```
Useful helper when "digging" through lot of Maybe fields, mirroring the usage of `?.` operator from some object-oriented languages.

Add `(%?)` composition operator

---

.github/workflows/haskell-ci.yml
template-haskell-optics/src/Language/Haskell/TH/Optics.hs
template-haskell-optics/template-haskell-optics.cabal

Make template-haskell-optics work with GHC 9.0 and 9.2

---

optics-core/src/Optics/Internal/Optic/TypeLevel.hs

* Allow the second argument of `AppendIndices` to be determined by the first and third arguments.
* Refine the documentation for `AppendIndices`. Due to the way incoherent instances work, the "short-circuit" path is actually treated as a fall-back; it will *only* be taken if nothing is known about the shape of the first list.

Better inference for AppendIndices

---

metametapost/src/MMP/Optics/Hierarchy.hs
metametapost/src/MMP/Optics/Indexed.hs
metametapost/src/MMP/Optics/Re.hs
optics-core/optics-core.cabal
optics-extra/CHANGELOG.md
optics-extra/optics-extra.cabal
optics-extra/src/Optics/Zoom.hs
optics-th/optics-th.cabal
optics/optics.cabal

This allow transformers-0.6 (and mtl-2.3) in install plans.
I tested locally that changes upstream don't affect optics. However, we can be 100% sure as e.g. `inspection-testing` depends on `ghc` which depends on `transformers`, so we cannot upgrade that package *and* run tests. Yet, I'm quite sure anyway, and will make revisions.
For reference, ghc to bundle transformers-0.6 issue: https://gitlab.haskell.org/ghc/ghc/-/issues/21587

Allow transformers-0.6

---

optics-extra/CHANGELOG.md
optics/CHANGELOG.md

Candidates:
* https://hackage.haskell.org/package/optics-extra-0.4.2/candidate
* https://hackage.haskell.org/package/optics-0.4.2/candidate

Release optics-extra-0.4.2 and optics-0.4.2

---

.github/workflows/haskell-ci.yml
cabal.haskell-ci
indexed-profunctors/indexed-profunctors.cabal
metametapost/metametapost.cabal
optics-core/optics-core.cabal
optics-extra/optics-extra.cabal
optics-sop/optics-sop.cabal
optics-th/optics-th.cabal
optics-th/tests/Optics/TH/Tests.hs
optics-vl/optics-vl.cabal
optics/optics.cabal
optics/tests/Optics/Tests/Core.hs
optics/tests/Optics/Tests/Labels/Generic.hs
optics/tests/Optics/Tests/Utils.hs
template-haskell-optics/CHANGELOG.md
template-haskell-optics/src/Language/Haskell/TH/Optics.hs
template-haskell-optics/template-haskell-optics.cabal

~~`template-haskell-optics` excluded for now.~~

Adapt optics for GHC 9.4

---

optics-extra/optics-extra.cabal

Tested using
cabal build --constraint='vector>=0.13' -w ghc-9.2.4
The `optics-extra` package has no tests.

Allow vector 0.13 series

---

optics-core/src/Optics/Iso.hs

`Optics.Iso` documentation linked to `Optics.Getter.review` which doesn't exist, instead of `Optics.Review.review`.

Fix `Optics.Review.review` link in docs for `Optics.Iso` module

---

optics/optics.cabal

_As far as I can tell_, this is no longer relevant: Hackage now has documentation for every module.
Although I can't actually find anything recent in the Cabal/Haddock/Hackage trackers/histories indicating when this was fixed.

Remove note about missing documentation for reexported modules

---

.github/workflows/haskell-ci.yml
indexed-profunctors/CHANGELOG.md
indexed-profunctors/indexed-profunctors.cabal
metametapost/metametapost.cabal
optics-core/CHANGELOG.md
optics-core/optics-core.cabal
optics-extra/optics-extra.cabal
optics-sop/optics-sop.cabal
optics-th/optics-th.cabal
optics-vl/optics-vl.cabal
optics/CHANGELOG.md
optics/optics.cabal
template-haskell-optics/template-haskell-optics.cabal

Release indexed-profunctors-0.1.1.1, optics-core-0.4.1.1 and optics-0.4.2.1

---

optics-th/optics-th.cabal

Support th-abstraction 0.6

---

.github/workflows/haskell-ci.yml
cabal.project
indexed-profunctors/indexed-profunctors.cabal
metametapost/metametapost.cabal
optics-core/optics-core.cabal
optics-extra/optics-extra.cabal
optics-sop/optics-sop.cabal
optics-th/optics-th.cabal
optics-vl/optics-vl.cabal
optics/optics.cabal
template-haskell-optics/template-haskell-optics.cabal

`template-haskell-optics` needs code changes, so I left it out.

Add GHC-9.10.1 to CI, allow containers-0.7

---

optics-core/src/Optics/Generic.hs
optics-core/src/Optics/Label.hs
optics/tests/Optics/Tests/Labels/Generic.hs

Add support for gafield as a label in GHC >= 9.6

---

optics/optics.cabal

Fixes #513.
In the same spirit as #410, this PR does **not** reexport `is` from the `Optics` module. I thought reexporting the `Optics.Core.Extras` module as `Optics.Extras` fit the style of the rest of the modules in the `optics` package better, however I am not opposed to reexporting as `Optics.Core.Extras` either.

Reexport `Optics.Core.Extras` from `optics` package

---

.github/workflows/haskell-ci.yml

Since 0.19.20250630 haskell-ci (i.e. today) has barebone support for conditionals in cabal.project
So now as `template-haskell-optics` haven't been updated for additions and changes bundled with GHC-9.12, it's conditionally included in `cabal.project`. And `haskell-ci` can handle that. (previously it would silently omit the package, so I needed
to edit cabal.project before running haskell-ci)

Update CI script
