well-typed/optics

- Makefile
- cabal.codegen.project
- codegen/Subtypes.hs
- codegen/Topograph.hs
- codegen/optics-codegen.cabal
- optics-core/src/Optics/Internal/Optic/Subtyping.hs
I'm not always adding new optic kinds... but when I do, I'd like a machine to help me.
`Topograph.hs` is an old work of mine, which I hadn't yet wrapped into a proper library.
> Codegen Is relation

- optics-core/src/Optics/Iso.hs
- Fixes doctest errors from #55
- Resolves #29
> Add a few util functions to Optics.Iso

- optics-core/src/Optics.hs
I listed few things,
@arybczak, do you have something to add?
> Add bullet points of differences to lens

- optics-core/src/Optics/Internal/AffineFold.hs
- optics-core/src/Optics/Internal/AffineTraversal.hs
- optics-core/src/Optics/Internal/Equality.hs
- optics-core/src/Optics/Internal/Fold.hs
- optics-core/src/Optics/Internal/Getter.hs
- optics-core/src/Optics/Internal/Iso.hs
- optics-core/src/Optics/Internal/IxFold.hs
- optics-core/src/Optics/Internal/IxSetter.hs
- optics-core/src/Optics/Internal/IxTraversal.hs
- optics-core/src/Optics/Internal/Lens.hs
- optics-core/src/Optics/Internal/Optic.hs
- optics-core/src/Optics/Internal/Prism.hs
- optics-core/src/Optics/Internal/Re.hs
- optics-core/src/Optics/Internal/Review.hs
- optics-core/src/Optics/Internal/Setter.hs
- optics-core/src/Optics/Internal/Traversal.hs
- optics-core/src/Optics/Optic.hs
- optics/tests/Optics/Tests.hs
> Add WithIx and NoIx type aliases

- optics-core/src/Optics/Iso.hs
- optics/src/Optics.hs
Also fix doctests and let `mapping` accept indexed Isos.
> Add coerced

- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/Internal/Fold.hs
- optics-core/src/Optics/Internal/IxFold.hs
- optics-core/src/Optics/Internal/IxTraversal.hs
- optics-core/src/Optics/Internal/Traversal.hs
- optics-core/src/Optics/IxFold.hs
- optics-core/src/Optics/IxTraversal.hs
- optics-core/src/Optics/Traversal.hs
> Add forOf, forOf_, iforOf, iforOf_

- optics-core/optics-core.cabal
- optics-core/src/GHC/Generics/Optics.hs
- optics-extra/optics-extra.cabal
> Move GHC.Generics to optics-core and generalize a few functions

- optics-core/src/Optics/AffineFold.hs
- optics-core/src/Optics/AffineTraversal.hs
- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/IxFold.hs
- optics-core/src/Optics/IxTraversal.hs
- optics-core/src/Optics/Lens.hs
- optics-th/src/Optics/TH/Internal/Product.hs
> Utilize monoidal structure of folds

- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/Indexed/Core.hs
- optics-core/src/Optics/Internal/Fold.hs
- optics-core/src/Optics/Internal/IxFold.hs
- optics-core/src/Optics/IxFold.hs
- optics-th/src/Optics/TH/Internal/Product.hs
> Rename (ix)foldVL to mk(Ix)(Fold)

- metametapost/metametapost.cabal
- optics/optics.cabal
See https://github.com/well-typed/optics/pull/157#issuecomment-488234245 for more info.
> Make optics-sop optional dependency

- optics-core/src/Data/Tuple/Optics.hs
- optics-core/src/Optics/Each/Core.hs
- optics-core/src/Optics/Indexed/Core.hs
- optics-core/src/Optics/Internal/Optic.hs
- optics-extra/src/Optics/Each.hs
- optics/src/Optics.hs
- optics/tests/Optics/Tests/Core.hs
- optics/tests/Optics/Tests/Utils.hs
With a fix for issue described in https://github.com/well-typed/optics/pull/160#issuecomment-493755474
> Infixl composition operators

- optics-core/src/Optics/AffineFold.hs
- optics-core/src/Optics/AffineTraversal.hs
- optics-core/src/Optics/At/Core.hs
- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/Getter.hs
- optics-core/src/Optics/Internal/Optic.hs
- optics-core/src/Optics/IxAffineFold.hs
- optics-core/src/Optics/IxAffineTraversal.hs
- optics-core/src/Optics/IxFold.hs
- optics-core/src/Optics/IxSetter.hs
- optics-core/src/Optics/IxTraversal.hs
- optics-core/src/Optics/Lens.hs
- optics-core/src/Optics/Prism.hs
- optics-core/src/Optics/Setter.hs
- optics-core/src/Optics/Traversal.hs
- optics-extra/src/Optics/Extra/Internal/Zoom.hs
Fixes #146.
@adamgundry what do you think?
> Remove toLens etc. functions, use castOptic instead

- optics-core/src/Data/Either/Optics.hs
- optics-core/src/Data/Map/Optics.hs
- optics-core/src/Data/Maybe/Optics.hs
- optics-core/src/Data/Set/Optics.hs
- optics-core/src/Data/Tuple/Optics.hs
- optics-core/src/GHC/Generics/Optics.hs
- optics-core/src/Optics/AffineTraversal.hs
- optics-core/src/Optics/Coerce.hs
- optics-core/src/Optics/Cons/Core.hs
- optics-core/src/Optics/Each/Core.hs
- optics-core/src/Optics/Empty/Core.hs
- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/Internal/Indexed.hs
- optics-core/src/Optics/Internal/Optic.hs
- optics-core/src/Optics/IxFold.hs
- optics-core/src/Optics/IxTraversal.hs
- optics-core/src/Optics/Lens.hs
- optics-core/src/Optics/Optic.hs
- optics-core/src/Optics/Prism.hs
- optics-core/src/Optics/Re.hs
- optics-core/src/Optics/Setter.hs
- optics-extra/src/Optics/Cons.hs
- optics-extra/src/Optics/Each.hs
- optics-extra/src/Optics/Empty.hs
- optics/src/Optics.hs
Based on comments from others at Well-Typed, I've rewritten the introduction in the `Optics` main module. In particular it now actually explains what optics are. Further feedback welcome.
> Rewrite introduction

- optics-core/src/Optics/LensyReview.hs
- optics-core/src/Optics/PrismaticGetter.hs
- optics/src/Optics.hs
Fixes #169, modulo a decision about renaming. I'm inclined to go for `ReLens` and `RePrism` but that will have to wait for another evening.
> Document LensyReview and PrismaticGetter properly

- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/Indexed/Core.hs
- optics-core/src/Optics/Internal/Fold.hs
- optics-core/src/Optics/Internal/IxFold.hs
- optics-core/src/Optics/IxFold.hs
- optics-th/src/Optics/TH/Internal/Product.hs
> Rename mkFold/mkIxFold to foldVL/ixFoldVL

- optics-core/src/Optics/Each/Core.hs
Ported from lens - https://github.com/ekmett/lens/pull/864
> Add Each Either instance

- optics-core/src/Optics/Internal/Indexed.hs
- optics-core/src/Optics/IxTraversal.hs
- optics/benchmarks/folds.hs
- optics/benchmarks/traversals.hs
- optics/optics.cabal
Looks like in the vast majority of cases we're either on par or slightly above `lens` in performance.
> Compare performance with lens in benchmarks

- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/Traversal.hs
- optics-extra/src/Data/Vector/Generic/Optics.hs
- optics-extra/src/Data/Vector/Optics.hs
> Remove occurences of both from documentation

- README.md
@arybczak @phadej @kosmikus Does this summary look okay to you? I'm happy to change how the authors etc. are presented...
The category of "officially supported packages" represents those that @arybczak and I plan to release soon. Do shout if you disagree.
> Update README with author/contributor information and package structure

- metametapost/src/MMP/Optics/Re.hs
- optics-core/src/Optics/Core.hs
- optics-extra/src/Optics/Operators/State.hs
- optics-th/src/Optics/TH.hs
- optics-th/tests/Optics/TH/Tests.hs
- optics/src/Optics.hs
- optics/tests/Optics/Tests/Labels.hs
> Export Optics.Operators by default

- metametapost/src/MetaMetaPost.hs
- optics-extra/optics-extra.cabal
- optics-extra/src/Optics/State.hs
- optics-extra/src/Optics/State/Operators.hs
- optics-extra/src/Optics/Zoom.hs
- optics/optics.cabal
- optics/src/Optics.hs
> Add function equivalents of operators in Optics.Operators.State

- optics-core/src/Optics/Operators.hs
> Add strict variations for operator versions of over/set/setJust

- optics-core/src/Data/IntMap/Optics.hs
- optics-core/src/Data/Map/Optics.hs
- optics-core/src/Optics/At/Core.hs
- optics-extra/src/Data/HashMap/Optics.hs
- optics-extra/src/Optics/At.hs
I had a moment of enlightenment 🧠
Whether using `at'` with `view` should force the value is debatable.
> Add at' that works for all At instances

- optics-core/src/Data/Tuple/Optics.hs
- optics-core/src/Optics/Lens.hs
- optics-th/src/Optics/TH.hs
For https://github.com/well-typed/optics/issues/196#issuecomment-508238418
> Add equality'

- optics-core/src/Data/IntMap/Optics.hs
- optics-core/src/Data/Map/Optics.hs
- optics-core/src/Data/Sequence/Optics.hs
- optics-core/src/Optics/AffineTraversal.hs
- optics-core/src/Optics/Each/Core.hs
- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/Internal/IxFold.hs
- optics-core/src/Optics/Iso.hs
- optics-core/src/Optics/IxAffineTraversal.hs
- optics-core/src/Optics/IxFold.hs
- optics-core/src/Optics/IxLens.hs
- optics-core/src/Optics/IxTraversal.hs
- optics-core/src/Optics/Lens.hs
- optics-core/src/Optics/Prism.hs
- optics-core/src/Optics/Traversal.hs
- optics-extra/src/Data/Vector/Generic/Optics.hs
- optics-extra/src/Optics/Each.hs
- optics-vl/src/Optics/VL.hs
- optics/src/Optics.hs
I renamed a few indexed functions to fit the `i*` pattern, improved some documentation and made `devoid` an indexed lens, because why not :thinking:
> A few improvements

- optics-core/src/Optics/AffineTraversal.hs
- optics-core/src/Optics/Iso.hs
- optics-core/src/Optics/IxAffineTraversal.hs
- optics-core/src/Optics/IxLens.hs
- optics-core/src/Optics/Lens.hs
- optics-core/src/Optics/Prism.hs
> Move VL construction functions back into VL section, add notes for visibility

- generic-optics/generic-optics.cabal
- optics-extra/optics-extra.cabal
> Bump allowed versions of hashable and generic-lens

- optics-extra/optics-extra.cabal
- optics-th/optics-th.cabal
- optics-vl/optics-vl.cabal
After uploading package candidates I spotted a few `.cabal` metadata tweaks needed.
> Cabal file tweaks

- README.md
- generic-optics/generic-optics.cabal
- optics-core/optics-core.cabal
- optics-extra/optics-extra.cabal
- optics-sop/optics-sop.cabal
- optics-th/optics-th.cabal
- optics-vl/optics-vl.cabal
- optics/optics.cabal
- template-haskell-optics/template-haskell-optics.cabal
> Release 0.1

- optics-core/src/Data/IntMap/Optics.hs
- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/IxFold.hs
- optics-core/src/Optics/IxGetter.hs
- optics-core/src/Optics/IxLens.hs
- optics-core/src/Optics/IxSetter.hs
- optics-core/src/Optics/IxTraversal.hs
- optics/src/Optics.hs
I'm very excited about optics packages. Thank you for the wonderfully documentation. In my world you've just won the "documentation of the year" award :laughing:  I especially like the idea of structuring the docs around formation/introduction/elimination and the subtyping diagrams, which will make it very easy for me to master the APIs. I wish more Haskell packages had docs like that.. 
May I ask what you're using to generate those hierarchy images?
EDIT: nevermind, I found the answer in the readme.
> Fix minor mistakes in haddocks

- generic-optics/generic-optics.cabal
- optics-extra/optics-extra.cabal
- optics-sop/optics-sop.cabal
- optics-th/optics-th.cabal
- optics-vl/optics-vl.cabal
- optics/optics.cabal
- template-haskell-optics/template-haskell-optics.cabal
Fixes #249. I'll change these on Hackage after this is merged.
> Tighten version bounds on subpackages

- optics-core/CHANGELOG.md
- optics-core/src/Optics/Iso.hs
Fixes #238 - I'm not sure if we want to have `non'` and `anon` though, they feel a bit weird to me. Any opinions?
> Add non, non' and anon

- optics/optics.cabal
> Build benchmarks on GHC 8.8

- optics-core/src/Optics/Getter.hs
- optics-core/src/Optics/Iso.hs
- optics-core/src/Optics/Lens.hs
- optics-core/src/Optics/Prism.hs
Fixes #263.
@ilyakooo0 thanks for flagging up the documentation errors here. Does this look better to you?
> Correct documentation for viewing type-changing optics

- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/IxFold.hs
- optics-core/src/Optics/IxTraversal.hs
- optics-core/src/Optics/Traversal.hs
- optics/benchmarks/traversals.hs
- optics/src/Optics.hs
- optics/tests/Optics/Tests/Misc.hs
> Add (i)singular

- optics-core/src/Optics/Optic.hs
Fixes https://github.com/well-typed/optics/issues/245.
> Export Curry/CurryCompose

- optics-core/src/Optics/Internal/Indexed.hs
> Add indexed instances for Const and Constant

- .travis.yml
- cabal.haskell-ci
- cabal.project
- metametapost/metametapost.cabal
- optics-sop/optics-sop.cabal
metametapost and optics-sop depend on generics-sop
> Test on CI without head.hackage

- codegen/Subtypes.hs
- optics-core/src/Optics/Internal/Optic.hs
- optics-core/src/Optics/Internal/Optic/Subtyping.hs
Should make it easier on the optimizer :thinking:
> Remove proxy argument from implies

- optics-core/src/Optics/Internal/Optic/Subtyping.hs
- optics-core/src/Optics/Internal/Optic/TypeLevel.hs
```haskell
λ> view (_1 % _Left)
<interactive>:163:1: error:
• An_AffineTraversal cannot be used as A_Getter
Perhaps you meant to use one of these:
‘preview’ (from Optics.AffineFold)
‘(^?)’ (from Optics.Operators)
‘over’ (from Optics.Setter)
‘(%~)’ (from Optics.Operators)
‘set’ (from Optics.Setter)
‘(.~)’ (from Optics.Operators)
• In the expression: view (_1 % _Left)
In an equation for ‘it’: it = view (_1 % _Left)
λ> view traversed
<interactive>:164:1: error:
• A_Traversal cannot be used as A_Getter
Perhaps you meant to use one of these:
‘traverseOf’ (from Optics.Traversal)
‘traverseOf_’ (from Optics.Fold)
‘foldMapOf’ (from Optics.Fold)
‘toListOf’ (from Optics.Fold)
‘(^..)’ (from Optics.Operators)
• In the expression: view traversed
In an equation for ‘it’: it = view traversed
λ> view …
```
> Show expected elimination forms on optic kind mismatch

- optics-core/CHANGELOG.md
- optics-core/optics-core.cabal
- optics-th/CHANGELOG.md
- optics-th/optics-th.cabal
Fixes #329.
I added changelogs with release date as 2020-08-05.
> Bump version of optics-core and optics-th to 0.3.0.1

- optics/src/Optics.hs
Are there any other resources worth linking to?
> Extend "Other resources" section of the Optics module docs

- optics-th/tests/Optics/TH/Tests/DuplicateRecordFields.hs
> Fix optics-th tests on GHC 8.10.2

- template-haskell-optics/src/Language/Haskell/TH/Optics.hs
I moved `_DataD` and `_NewtypeD` to reduce the diff and corrected a few conditional type signatures.
> Synchronize a bit more with Language.Haskell.TH.Lens

- template-haskell-optics/CHANGELOG.md
> Release template-haskell-optics-0.1

- optics-th/tests/Optics/TH/Tests.hs
> Test makePrismLabels after declareFieldLabels

- optics-core/src/Optics/Internal/Optic.hs
- optics-core/src/Optics/Internal/Optic/TypeLevel.hs
- optics-core/src/Optics/Optic.hs
- optics/tests/Optics/Tests/Core.hs
Parts of #353 for tidying up the `AppendIndices` bit.
> Tidy up AppendIndices

- optics-th/optics-th.cabal
> Allow th-abstraction-0.4

- .travis.yml
- indexed-profunctors/indexed-profunctors.cabal
- metametapost/metametapost.cabal
- optics-core/optics-core.cabal
- optics-core/src/Optics/At/Core.hs
- optics-core/src/Optics/Internal/Indexed/Classes.hs
- optics-core/src/Optics/Internal/Optic.hs
- optics-extra/optics-extra.cabal
- optics-sop/optics-sop.cabal
- optics-th/optics-th.cabal
- optics-vl/optics-vl.cabal
- optics/benchmarks/traversals.hs
- optics/optics.cabal
- optics/tests/Optics/Tests/Core.hs
- optics/tests/Optics/Tests/Misc.hs
- optics/tests/Optics/Tests/Utils.hs
- template-haskell-optics/src/Language/Haskell/TH/Optics.hs
- template-haskell-optics/template-haskell-optics.cabal
Needed by #361 and #288, complicates #362. It's been 4 years and 5 (6th almost there) major GHC versions since then, it's time.
> Drop support for GHC 8.0

- optics-th/src/Optics/TH/Internal/Product.hs
- optics-th/src/Optics/TH/Internal/Sum.hs
- optics-th/src/Optics/TH/Internal/Utils.hs
- optics-th/tests/Optics/TH/Tests.hs
Fix from https://github.com/ekmett/lens/pull/945#issuecomment-723581419.
> Fix TH generation of optics for poly-kinded data families

- optics-core/src/Optics/Label.hs
- optics-th/src/Optics/TH.hs
- optics-th/src/Optics/TH/Internal/Product.hs
- optics-th/src/Optics/TH/Internal/Sum.hs
- optics-th/src/Optics/TH/Internal/Utils.hs
- optics-th/tests/Optics/TH/Tests.hs
> Support labels for polymorphic fields / existential constructors / more type-changing updates

- indexed-profunctors/src/Data/Profunctor/Indexed.hs
- optics-core/src/Optics/Internal/Bi.hs
- optics-core/src/Optics/Internal/Fold.hs
- optics-core/src/Optics/Internal/Indexed.hs
- optics-core/src/Optics/Internal/Optic.hs
- optics-core/src/Optics/Internal/Optic/TypeLevel.hs
- optics-core/src/Optics/Internal/Utils.hs
- optics/tests/Optics/Tests/Labels/Generic.hs
> Reduce the amount of INLINE pragmas in indexed-profunctors and optics-core

- optics-extra/optics-extra.cabal
> Relax bytestring bounds

- migration-guide-0.4.md
- optics-core/CHANGELOG.md
- optics-core/src/Optics/Internal/Optic/Subtyping.hs
- optics-core/src/Optics/Internal/Optic/TypeLevel.hs
- optics-core/src/Optics/IxLens.hs
- optics-core/src/Optics/Label.hs
- optics-extra/CHANGELOG.md
- optics-th/CHANGELOG.md
- optics/CHANGELOG.md
See #375. This adds a few missing changelog entries. Anything else we need to change before the release?
> Add changelogs for 0.4 release

- optics/benchmarks/folds.hs
- optics/benchmarks/traversals.hs
- optics/optics.cabal
Runs faster, has less dependencies.
> Use tasty-bench instead of criterion

- optics-core/src/Optics/Label.hs
@adamgundry can you please confirm that the update is accurate?
> Update documentation of Optics.Label

- optics-core/CHANGELOG.md
- optics-core/optics-core.cabal
- optics-core/src/Data/Maybe/Optics.hs
- optics-core/src/Optics/Core/Extras.hs
- optics-core/src/Optics/Fold.hs
- optics-core/src/Optics/Setter.hs
- optics-core/src/Optics/Traversal.hs
- optics-extra/CHANGELOG.md
- optics-extra/optics-extra.cabal
- optics-th/CHANGELOG.md
- optics-th/optics-th.cabal
- optics/CHANGELOG.md
- optics/optics.cabal
> Release optics-core-0.4.1, optics-extra-0.4.1, optics-th-0.4.1, optics-0.4.1

- .github/workflows/haskell-ci.yml
- optics/optics.cabal
- optics/tests/Optics/Tests/Core.hs
- optics/tests/Optics/Tests/Utils.hs
Testing https://github.com/nomeata/inspection-testing/pull/67
> Use inspection-testing-0.5

- .github/workflows/haskell-ci.yml
- indexed-profunctors/indexed-profunctors.cabal
- metametapost/metametapost.cabal
- optics-core/optics-core.cabal
- optics-extra/optics-extra.cabal
- optics-sop/optics-sop.cabal
- optics-th/optics-th.cabal
- optics-vl/optics-vl.cabal
- optics/optics.cabal
- optics/tests/Optics/Tests/Labels/Generic.hs
- template-haskell-optics/template-haskell-optics.cabal
9.4.1 job needs https://github.com/well-typed/generics-sop/pull/156.
> Test with GHC 9.4.1

- optics/src/Optics.hs
> traverals -> traversals

- indexed-profunctors/src/Data/Profunctor/Indexed.hs
- optics-core/src/Optics/Internal/Optic.hs
- optics/tests/Optics/Tests/Core.hs
> Add inline pragmas to small functions that really should inline

- optics-extra/src/Data/HashSet/Optics.hs
See https://github.com/well-typed/optics/pull/495#issuecomment-1720103258
> Fix doctest for HashSet

- .github/workflows/haskell-ci.yml
- indexed-profunctors/indexed-profunctors.cabal
- metametapost/metametapost.cabal
- optics-core/optics-core.cabal
- optics-extra/optics-extra.cabal
- optics-sop/optics-sop.cabal
- optics-th/optics-th.cabal
- optics-vl/optics-vl.cabal
- optics/optics.cabal
- template-haskell-optics/src/Language/Haskell/TH/Optics.hs
- template-haskell-optics/template-haskell-optics.cabal
> Allow GHC-9.8, upgrade tested-with, haskell-ci

- optics-core/src/Optics/Internal/Optic/TypeLevel.hs
it's not a workhorse for composition, so no need to have an extra equation
> Define Append canonically
